name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'   # जरूरी field जो error को हटाएगी

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'

      - run: flutter pub get
      - run: flutter build apk --release

      - uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk
